---
title: "Academic CV"
---

## Education

King's College London \| PhD - Statistics \| Sept 2022 - Present

University of St. Andrews \| MMath - Statistics (1st) \| Sept 2016 - June 2020

## Experience

Bank of America Merrill Lynch \| Software Engineer \| August 2020 - September 2022

British Army Reserve \| Troop Leader \| June 2017 - June 2020

## Publications

McKee, C. & Kalli, M. (2025) Network Modelling of Asynchronous Change-Points in Multivariate Time Series. (In review, available on [Arxiv](https://arxiv.org/abs/2506.15801).)

## Talks and Posters

**24/06/2024 (Poster) UCLA:** Network Modelling of Asynchronous Change-Points in Multivariate Time Series.

**26/02/202 (Invited Talk) UCL:** Network Modelling of Asynchronous Change-Points in Multivariate Time Series.

**15/12/2024 (Invited Talk)** **CFE CMStatistics:** Mutually Dependent Bernoulli Processes for Multivariate Change-Point Detection.

**05/06/2024 (Poster) ISBA World Meeting Venice:** Bayesian Nonparametric Change-Point Detection for Multivariate Time Series.

**04/06/2024 (Contributed Talk) ISBA World Meeting Venice:** Bayesian Nonparametric Change-Point Detection for Multivariate Time Series.

**05/12/2023 (Poster) ISBA BNP Melbourne:** Bayesian Nonparametric Change-Point Modelling for Macroeconomic Time Series.

## Funding and Awards

-   My PhD is funded by a 4-year studentship from the Heilbronn Institute for Mathematical Research.

-   \$500 travel grant to present at the 14th International Conference on Bayesian Nonparametrics (2025, UCLA).

-   \$500 travel grant to present at ISBA BNP (Melbourne, 2023).

-   Best poster award at ISBA World Meeting (Venice, 2024).
